name: itertools
description: Package for advanced simple and easy work with Dart iterators
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple: '>=2.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
