name: itertools
description: Package for advanced simple and easy work with Dart iterators
version: 0.1.2
homepage: https://github.com/avdosev
repository: https://github.com/avdosev/itertools_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple_dart: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
